# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ExpoContactsExample' do
  # use_frameworks!

  # Pods for ExpoContactsExample
  pod 'EXContacts', path: '../node_modules/expo-contacts/ios'

end
